### ISSUE TITLE
CAPS letters doesn't getting write down

### ISSUE THREAD

**Issue by SpookyToad2** [QFSW/Pyanoboard#6]
When i've tried to make config that writes big letters, it just writes down smol ones.

**Comment by QFSW** [comment]
Hi @SpookyToad2, Pyanoboard is for simulating key presses and not characters, and there isn't a key for capital letters. You could try having caps lock on, or bind shift in addition to the key you wish to use

**Comment by SpookyToad2** [comment]
Oh good news. Tried to shift + key to the same note and it worked!

    {
      "note": "C3",
      "key": "shift"
    },
    {
      "note": "C3",
      "key": "t"
    },
